services:
  - mysql:5.7

variables:
  MYSQL_RANDOM_ROOT_PASSWORD: "yes"
  MYSQL_HOST: mysql
  MYSQL_DATABASE: bitrix-ci
  MYSQL_USER: bitrix-ci
  MYSQL_PASSWORD: bitrix-ci

before_script:
  - apt-get update -yqq && apt-get install -yqq zip unzip
  - docker-php-ext-install mysqli
  - curl https://getcomposer.org/installer | php --
  - php composer.phar install --no-interaction

PHP 5.6:
  image: php:5.6
  script: vendor/bin/phpunit

PHP 7.0:
  image: php:7.0
  script: vendor/bin/phpunit

PHP 7.1:
  image: php:7.1
  script: vendor/bin/phpunit

PHP 7.2:
  image: php:7.2
  script: vendor/bin/phpunit

PHP 7.3:
  image: php:7.3
  script: vendor/bin/phpunit