version: "3"
services:
  bitrix:
    image: webdevops/php-nginx-dev:5.6
    volumes:
      - ./:/app/
    ports:
      - 80:80
    environment:
      WEB_DOCUMENT_ROOT: /app/src/
      php.short_open_tag: 1
      php.mbstring.func_overload: 2
      php.display_errors: 1
      MYSQL_HOST: mysql
      MYSQL_DATABASE: bitrix-ci
      MYSQL_USER: bitrix-ci
      MYSQL_PASSWORD: bitrix-ci
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: bitrix-ci
      MYSQL_USER: bitrix-ci
      MYSQL_PASSWORD: bitrix-ci