services:
  bitrix:
    image: docker.io/webdevops/php-apache-dev:${PHP-8.3}
    volumes:
      - ./:/app/
    working_dir: /app/
    depends_on:
      - mysql
    ports:
      - ${HTTP_PORT-8080}:80
    environment:
      WEB_DOCUMENT_ROOT: /app/public/
      php.short_open_tag: 1
      php.display_errors: 0
      php.max_input_vars: 10000
      php.memory_limit: "256M"
      php.date.timezone: "Europe/Moscow"
      MYSQL_HOST: "mysql"
      MYSQL_DATABASE: "bitrix-ci"
      MYSQL_USER: "bitrix-ci"
      MYSQL_PASSWORD: "bitrix-ci"
      DEBUG: 1
      POSTFIX_RELAYHOST: "[mailhog]:1025"
  mysql:
    image: docker.io/library/mysql:5.7
    volumes:
      - ./var/mysql/:/var/lib/mysql/
    ports:
      - ${MYSQL_PORT-3306}:3306
    command: >-
      --default-time-zone=Europe/Moscow
      --character-set-server=utf8
      --collation-server=utf8_unicode_ci
      --skip-innodb-strict-mode
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: "bitrix-ci"
      MYSQL_USER: "bitrix-ci"
      MYSQL_PASSWORD: "bitrix-ci"
  mailhog:
    image: docker.io/mailhog/mailhog
    ports:
      - ${MAILHOG_HTTP_PORT-8025}:8025
