name: PHPUnit
on: [push]
jobs:
  PHPUnit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PHP: ["5.6", "7.0", "7.1", "7.2", "7.3", "7.4"]
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: PHP=${{ matrix.PHP }} docker-compose run -T bitrix composer install --no-ansi --no-interaction --no-suggest --no-progress --prefer-dist

      - name: Run PHPUnit
        run: PHP=${{ matrix.PHP }} docker-compose run -T bitrix vendor/bin/phpunit
