name: PHPUnit
on: [push]
jobs:
  PHPUnit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        PHP: ["7.1", "7.2", "7.3", "7.4"]
    container:
      image: webdevops/php-dev:${{ matrix.PHP }}
      env:
        MYSQL_HOST: mysql
        MYSQL_DATABASE: bitrix-ci
        MYSQL_USER: bitrix-ci
        MYSQL_PASSWORD: bitrix-ci
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_RANDOM_ROOT_PASSWORD: "yes"
          MYSQL_DATABASE: bitrix-ci
          MYSQL_USER: bitrix-ci
          MYSQL_PASSWORD: bitrix-ci
    steps:
      - name: Checkout source
        uses: actions/checkout@v1

      - name: Set up environment
        run: |
          echo 'short_open_tag=1' >> /opt/docker/etc/php/php.ini
          echo 'mbstring.func_overload=2' >> /opt/docker/etc/php/php.ini
          cat /opt/docker/etc/php/php.ini

      - name: Install dependencies
        run: composer install --no-ansi --no-interaction --no-suggest --no-progress --prefer-dist

      - name: Run PHPUnit tests
        run: php vendor/bin/phpunit
